chat/urls.py
from django.urls import path
from chat.views import(
	message_view,
	inbox_view,
	new_chat_list,
	new_chat,
	delete_chat,
	delete_message,

)


app_name = 'chat'


urlpatterns = [
	path('<slug>/', message_view, name="message"),
	path('account/inbox', inbox_view, name="inbox"),
	path('new', new_chat_list, name="new"),
	path('new/<slug>/', new_chat, name="new_chat"),
	path('<id>/dc/delete', delete_chat, name="delete_chat"),
	path('<slug>/dm/<id>', delete_message, name="delete_message"),

]

chat/models.py
from django.db import models
from django.conf import settings



STATUS_CHOICES = (
    (1, "Sent"),
    (2, "Seen"),
)

DELETEFOR_CHOICES = (
    (1, "DELETED for user01"),
    (2, "DELETED for user02"),
)


class Chat(models.Model):
	started 			= models.DateTimeField(auto_now_add=True, editable=False)
	user01				= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user01_chat', null=True)
	user02				= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user02_chat', null=True)
	deletefor			= models.IntegerField(choices=DELETEFOR_CHOICES, null = True, blank=True, default=0)
	

	def get_last_message(self):
		message = Message.objects.filter(deletefor=0).filter(chat=self).last()
		return message if message else ""

	def get_last_message_timestamp(self):
		message = Message.objects.filter(chat=self).last()
		return message.timestamp if message else ""

	def get_chat_delete_details(self):
		return self.deletefor

class Message(models.Model):
	message_body		= models.CharField(max_length=2200, blank=False)
	image				= models.ImageField(null=True, blank=True)
	timestamp			= models.DateTimeField(auto_now=True, editable=False)
	chat 				= models.ForeignKey(Chat, on_delete=models.CASCADE)
	message_sender		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='message_sender', null=True)
	status				= models.IntegerField(choices=STATUS_CHOICES, default=1)
	delete_by_sender	= models.BooleanField(default=False)
	delete_by_receiver	= models.BooleanField(default=False)
	
	def __str__(self):
		return self.message_body

	def sender(self):
		return self.sender

	def message(self):
		return self.message

chat/forms.py
from django import forms
from chat.models import Chat, Message
from django.db.models import Q
from django.http import request



class CreateChatMessage(forms.ModelForm):
	

	class Meta:
		model = Message
		fields = ['message_body', 'message_sender', 'chat']

chat/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.views.decorators.cache import cache_control
from chat.forms import CreateChatMessage
from chat.models import Chat, Message
from account.models import Account
from django.db.models import Q
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def message_view(request, slug):
	user = request.user

	context = {}

	if not user.is_authenticated:
		return redirect('login')

	user_profile = Account.objects.get(slug=slug)
	context['user_profile'] = user_profile
	try:
		chat = Chat.objects.get(
			Q(user01=user, user02=user_profile) | Q(user01=user_profile, user02=user)
		)
		context['chat'] = chat
	except Chat.DoesNotExist:
		return redirect("add_chat", user_profile.slug)

	try:
		# Querying All Messages
		messages = Message.objects.filter(chat=chat)
		context['messages'] = messages
		# Querying Non-Deleted Messages

		update_message_status = Message.objects.filter(chat=chat).filter(message_sender=user_profile).update(status=2)
	except Message.DoesNotExist:
		return None
	form = CreateChatMessage(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		message_body = form.cleaned_data.get('message_body')
		obj.message_body = message_body
		obj.save()
		form = CreateChatMessage()
		return redirect('chat:message', user_profile.slug)

	return render(request, 'chat/messages.html', context)

@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def inbox_view(request):
	user = request.user

	context = {}

	if not user.is_authenticated:
		return redirect('login')

	try:
		chats = Chat.objects.filter(
			Q(user01=user) | Q(user02=user)
		)
	except Chat.DoesNotExist:
		return redirect("home")

	messages = Message.objects.filter(chat__in=chats).last()

	context['messages'] = messages

	context['chats'] = chats

	return render(request, 'chat/inbox.html', context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def new_chat_list(request):
	user = request.user

	context = {}

	accounts = Account.objects.all().exclude(username=user.username)

	context['accounts'] = accounts

	return render(request, 'chat/new_chat_list.html', context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def new_chat(request, slug):
	user = request.user

	context = {}

	user_profile = Account.objects.get(slug=slug)

	try:
		chat = Chat.objects.get(
			Q(user01=user, user02=user_profile) | Q(user01=user_profile, user02=user)
		)
	except Chat.DoesNotExist:
		chat = Chat.objects.get_or_create(
			user01 = user,
			user02 = user_profile
		)

	context['response'] = "Chat Created Successfully"

	return redirect('chat:message', slug=user_profile.slug)


def delete_chat(request, id):
	user = request.user

	if not user.is_authenticated:
		return redirect('home')

	try:
		chat = Chat.objects.get(id=id)
	except Chat.DoesNotExist:
		return redirect('chat:inbox')

	
	if chat.deletefor is None:
		if chat.user01 == user:
			Chat.objects.filter(id=id).update(deletefor=1)
		else:
			Chat.objects.filter(id=id).update(deletefor=2)
	else:
		chat.delete()

	return redirect('chat:inbox')


def delete_message(request, id, slug):
	user = request.user

	if not user.is_authenticated:
		return redirect('home')

	user_profile = Account.objects.get(slug=slug)

	message = Message.objects.get(id=id)

	message_sender = message.message_sender

	if message_sender == user:
		message.delete_by_sender = True
		message.save()
	else:
		message.delete_by_receiver = True
		message.save()

	if message.delete_by_receiver == True and message.delete_by_sender == True:
		message.delete()

	return redirect('chat:message', user_profile.slug)

chat/templates/chat/inbox.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<style type="text/css">
	.user_image {
  		border-radius: 50%;
  	}
  	p {
  		color: 	#ababab;
  		font-size: 13px;
	}
	.main-content{
		 box-shadow: 0 0 13px rgba(0, 0, 0, 0.4);
	}
	
	.new-chat{
		margin-left: auto;
		margin-top: auto;
		margin-right: 10px
	}
	.title{
		margin-left: 15px;
		margin-top: auto;
	}
</style>


<div class="container">


	<div class="col-sm-8 offset-sm-2 main-content" style="background-color: white; border-radius: 20px;">
		<div class="row">
			<h4 class="mt-3 mb-0 title" style="font-size: 17px;">Messages</h4>
			<a class="new-chat" href="{% url 'chat:new' %}"><svg height="30px" width="30px" viewBox="0 0 36 36"><g id="compose" fill="none" fill-rule="evenodd" stroke="none" stroke-width="1"><polygon id="Fill-1" points="0 36 36 36 36 0 0 0"></polygon><path id="Fill-2" d="M15.047,20.26245 L15.9815,17.45445 C16.091,17.12495 16.276,16.82495 16.5215,16.57945 L27.486,5.60195 C28.29,4.79695 29.595,4.79695 30.399,5.60195 C31.2025,6.40645 31.202,7.70895 30.399,8.51345 L19.432,19.49345 C19.186,19.73945 18.886,19.92495 18.556,20.03495 L15.7555,20.96995 C15.318,21.11645 14.901,20.69995 15.047,20.26245 Z M24.005,28.00095 L12.001,28.00095 C9.791,28.00095 8,26.20945 8,23.99995 L8,11.99895 C8,9.78945 9.791,7.99845 12.001,7.99845 L19.0035,7.99745 C19.5555,7.99745 20.0035,8.44545 20.0035,8.99745 C20.0035,9.54995 19.5555,9.99795 19.0035,9.99795 L12.001,9.99845 C10.8965,9.99845 10.0005,10.89395 10.0005,11.99895 L10.0005,23.99995 C10.0005,25.10445 10.8965,26.00045 12.001,26.00045 L24.005,26.00045 C25.1095,26.00045 26.005,25.10445 26.005,23.99995 C26.005,23.99995 26.0045,17.55145 26.0045,16.99895 C26.0045,16.44645 26.4525,15.99845 27.005,15.99845 C27.557,15.99845 28.005,16.44645 28.005,16.99895 C28.005,17.55145 28.0055,23.99995 28.0055,23.99995 C28.0055,26.20945 26.2145,28.00095 24.005,28.00095 Z" fill="#000000"></path></g></svg></a>
		</div>
		<hr class="mt-2">
		{% for chat in chats %}
			{% if chat.user01 == request.user and chat.deletefor != 1 %}
				<div class="row">
					{% if chat.get_last_message != '' %}
					<a style="text-decoration: none; font-size: 13px;" class="text-dark" href="{%url 'chat:message' chat.user02.slug %}">
						<img class="user_image mx-2 mb-3" width= 40px height= 40px src="{{chat.user02.profile_picture.url}}">
					</a>
					<div class="col">
						
						{% if chat.get_last_message.message_sender == request.user %}
							<a style="text-decoration: none; font-size: 13px;" class="text-dark align-text-bottom" href="{%url 'chat:message' chat.user02.slug %}">{{chat.user02.username}}</a>
							<p class="align-text-top">You:{{chat.get_last_message|truncatechars:100}}</p>
						{% else %}
							{% if chat.get_last_message.status == 1 %}
								<a style="text-decoration: none; font-size: 13px;" class="text-dark align-text-bottom" href="{%url 'chat:message' chat.user02.slug %}"><b>{{chat.user02.username}}</b></a>
								<p class="align-text-top" style="color: #525252"><b>{{chat.get_last_message|truncatechars:30}}</b></p>
							{% else %}
								<a style="text-decoration: none; font-size: 13px;" class="text-dark align-text-bottom" href="{%url 'chat:message' chat.user02.slug %}">{{chat.user02.username}}</a>
								<p class="align-text-top">{{chat.get_last_message|truncatechars:30}}</p>
							{% endif %}
						{% endif %}
						
						


						<!-- <p>{{chat.get_last_message_timestamp}}</p> -->

					</div>
						<div id="message_extras">
<!-- 							<a class="ml-auto" href="{%url 'chat:delete_chat' id=chat.id %}">Remove</a> -->
							<span data-toggle="modal" data-target="#exampleModalCenter" class="dropdown-btn mr-2">•••</span>
						</div>
					{% endif %}
				</div>


			{% elif chat.user02 == request.user and chat.deletefor != 2 %}
				<div class="row">
					{% if chat.get_last_message != '' %}
					<a style="text-decoration: none; font-size: 13px;" class="text-dark" href="{%url 'chat:message' chat.user01.slug %}">
						<img class="user_image mx-2 mb-3" width= 40px height= 40px src="{{chat.user01.profile_picture.url}}">
					</a>
					<div class="col">
						{% if chat.get_last_message.message_sender == request.user%}
							<a style="text-decoration: none; font-size: 13px;" class="text-dark align-text-bottom" href="{%url 'chat:message' chat.user01.slug %}">{{chat.user01.username}}</a>
							<p class="align-text-top" style="color: #525252">You:{{chat.get_last_message}}</p>
						{% else %}
							{% if chat.get_last_message.status == 1 %}
								<a style="text-decoration: none; font-size: 13px;" class="text-dark align-text-bottom" href="{%url 'chat:message' chat.user01.slug %}"><b>{{chat.user01.username}}</b></a>
								<p class="align-text-top" style="color: #525252"><b>{{chat.get_last_message}}</b></p>
							{% else %}
								<a style="text-decoration: none; font-size: 13px;" class="text-dark align-text-bottom" href="{%url 'chat:message' chat.user01.slug %}">{{chat.user01.username}}</a>
								<p class="align-text-top" >{{chat.get_last_message}}</p>
							{% endif %}

						{% endif %}
						
					</div>
					{% endif %}
					<div id="message_extras">
						<span data-toggle="modal" data-target="#exampleModalCenter" class="dropdown-btn mr-2">•••</span>
					</div>
				</div>

			{% endif %}

	{% endfor %} 
	</div>

</div>


{% endblock %}

chat/templates/chat/messages.html
{% extends 'base.html' %}

{% load static %}

{% load chat_extras %}

{% block content %}



<style type="text/css">
  .create-form {
	    padding: 15px;
	    margin: auto;
  	}
  	.submit-button{
  		max-width: 70px;
  	}
  	.user_image {
  		border-radius: 50%;
  	}
  	p {
  		/*color: 	#ababab;*/
  		font-size: 13px;
	}
	.main-content{
		 box-shadow: 0 0 13px rgba(0, 0, 0, 0.4);
	}
	.other-user-msg{
		background-color: white;
		border: 1.5px #f0f0f0 solid;
		border-radius: 20px;
		padding: 7px 13px;
		max-width: 250px
		/*margin-right: 420px;*/
	}
	.current-user-msg{
		background-color: #f5f5f5;
		border-radius: 20px;
		padding: 7px 13px;
		max-width: 250px
		/*margin-left: 420px;*/
	}
	::placeholder {
  		color: #a3a3a3;
	}
	.other-user-msg.first_message{
		border-bottom-left-radius: 0;
		margin-left: 42px;
	}
	.other-user-msg.mid_message{
		border-top-left-radius: 0;
		border-bottom-left-radius: 0;
		margin-left: 42px;
	}
	.other-user-msg.last_message{
		border-top-left-radius: 0;
	}
	.current-user-msg.first_message{
		border-bottom-right-radius: 0;
	}

	.current-user-msg.mid_message{
		border-top-right-radius: 0;
		border-bottom-right-radius: 0;
	}
	.current-user-msg.last_message{
		border-top-right-radius: 0;
	}
/*
	#message_extras{
    	display: none;
	}

	p:hover + #message_extras, #message_extras:hover {
    	display: block;
	}
*/
</style>




<div class="container">

	<div class="col-md-8 offset-md-2 col-lg-10 offset-lg-1 main-content" style="background-color: white; border-radius: 20px;">
		<div class="row justify-content-start">
			<img class="user_image mt-3 mb-0 ml-4" width= 60px height= 60px src="{{user_profile.profile_picture.url}}">
			<p class="ml-2 mt-3 ">{{user_profile.username}}</p>
		</div>
		<hr>

		{% for message in messages %}
			{% with next_element=messages|next:forloop.counter0 %}
			{% with previous_element=messages|previous:forloop.counter0 %}

			{% if message.message_sender == request.user and message.delete_by_sender == False %}
				<div class="row" >
					<div class="col">
						<div onmouseenter="myEnterFunction()">
							{% if next_element.message_sender == user_profile and previous_element.message_sender == request.user or next_element == '' and previous_element.message_sender == request.user%}
								<p class="current-user-msg last_message float-right mb-1" data-toggle="tooltip" data-placement="top" title="{{message.timestamp}}">{{message}}</p>
							{% elif previous_element.message_sender == request.user and next_element.message_sender == request.user%}
								<p class="current-user-msg mid_message float-right mb-1" data-toggle="tooltip" data-placement="top" title="{{message.timestamp}}">
								{{message}}</p>

							{% elif previous_element.message_sender == null or previous_element.message_sender == user_profile and next_element.message_sender == user_profile or next_element.message_sender == null %}
								<p class="current-user-msg float-right mb-1" data-toggle="tooltip" data-placement="top" title="{{message.timestamp}}">{{message}}</p>
							{% elif previous_element.message_sender == null or previous_element.message_sender == user_profile and next_element.message_sender == request.user %}
								<p class="current-user-msg first_message float-right mb-1" data-toggle="tooltip" data-placement="top" title="{{message.timestamp}}">{{message}}</p>
							
							

							{% endif %}
							<div id="message_extras">
								<p data-toggle="tooltip" data-placement="top" title="Remove" class="float-right mr-2" id="delete_message"><a href="{%url 'chat:delete_message' id=message.id slug=user_profile.slug %}"><img src="{% static 'delete.png' %}"></a>
								
									
								</p>
							</div>
							<!-- <p data-toggle="tooltip" data-placement="top" title="Remove" class="float-right mr-2" id="delete_message"><a href="{%url 'chat:delete_message' id=message.id slug=user_profile.slug  %}">Remove</a></p> -->
						</div>
						
					</div>
				</div>


			{% elif message.message_sender == user_profile and message.delete_by_receiver == False %}
				<div class="row">
					<a style="text-decoration: none; font-size: 13px;" class="text-dark" href="#">

    					
						{% if next_element.message_sender == request.user or next_element == '' %}
							<img data-toggle="tooltip" data-placement="left" title="{{user_profile.username}}" class="user_image ml-2 mr-0" width= 35px height= 35px src="{{user_profile.profile_picture.url}}">
						{% elif chat.get_last_message_message_sender == user_profile %}


						{% endif %}
						
						
						
					</a>
					<div class="col">
						{% if next_element.message_sender == request.user or next_element == '' %}
							<p data-toggle="tooltip" data-placement="top" title="{{message.timestamp}}" class="other-user-msg last_message float-left mb-1 ml-0" >{{message}}</p>
							<!-- <div id="message_extras">
								<p data-toggle="tooltip" data-placement="top" title="Remove" class="float-left ml-2" id="delete_message"><a href="{%url 'chat:delete_message' id=message.id slug=user_profile.slug  %}"><img src="{% static 'delete.png' %}"></a>
								
									
								</p>
							</div> -->

						{% elif previous_element.message_sender == user_profile and next_element.message_sender == user_profile%}
							<p data-toggle="tooltip" data-placement="top" title="{{message.timestamp}}" class="other-user-msg mid_message float-left mb-1" >{{message}}</p>


						{% else %}
							<p data-toggle="tooltip" data-placement="top" title="{{message.timestamp}}" class="other-user-msg first_message float-left mb-1">{{message}}</p>



						{% endif %}
						
					</div>

				</div>
			{% endif %}
			{% endwith %}
			{% endwith %}
		{% endfor %} 

		<div class="row">
			<form class="create-form" id="myForm" method="post" enctype="multiparts/form-data">{% csrf_token %}

				<!-- Body -->
				
				<div class="form-group" id="form_id">
					<!-- <label for="id_message_body">Message</label>
					<textarea class="form-control" rows="2" type="text" name="message_body" id="id_message_body" placeholder="Enter message here..." required></textarea> -->
					<div class="col-sm-10 offset-sm-1">
						<div class="row">
							<input class="form-control" type="text" style="background-color: #f5f5f5; border-radius: 20px; border: 1px solid #f5f5f5" name="message_body" id="message_bodyInput" placeholder="Type a message...">
							<button class="submit-button btn-block" type="submit">Send</button>
						</div>
					</div>
					<input type="hidden" name="message_sender" id="message_senderInput" placeholder="Sender..." value="{{request.user.id}}">
					<input type="hidden" name="chat" id="chatInput" placeholder="Write a message..." value="{{chat.id}}">
				</div>
				

				<!-- Image -->
				<!-- <div class="form-group">
					<label for="id_image">Image</label>
					<input  type="file" name="image" id="id_image" accept="image/*">
				</div> -->

				<!-- Submit btn -->
				
			</form>	
			
		</div>
	</div>

</div>


{% endblock %}

<script type="text/javascript">
	$(function () {
  		$('[data-toggle="tooltip"]').tooltip()
	})
</script>

chat/templates/chat/new_chat.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
	<div class="col-sm-8 offset-sm-2" style="background-color: white; border-radius: 20px;">
		<div class="row justify-content-center">
			<h4 class="mt-3 mb-0" style="font-size: 17px">{{response}}</h4>
		</div>

		
	</div>


</div>





{% endblock %}

chat/templates/chat/new_chat_list.html
{% extends 'base.html' %}


{% block content %}


<style type="text/css">
	.user_image {
  		border-radius: 50%;
  		width: 40px;
  		height: 40px;
  		
  	}
</style>

<div class="container">
	{% for account in accounts %}
		<div class="row">
			<img class="user_image" src="{{account.profile_picture.url}}">
			<p>{{account.username}}</p>
		</div>


	{% endfor %}
</div>



{% endblock %}