activity/urls.py
from django.urls import path
from activity.views import (
	all_notification_view,
	request_notification_view,
)



app_name = 'activity'


urlpatterns = [
	path('all/', all_notification_view, name='notifications'),
	path('requests/', request_notification_view, name='request_notifications')
]

chat/urls.py
from django.urls import path
from chat.views import(
	message_view,
	inbox_view,
	new_chat_list,
	new_chat,
	delete_chat,
	delete_message,

)


app_name = 'chat'


urlpatterns = [
	path('<slug>/', message_view, name="message"),
	path('account/inbox', inbox_view, name="inbox"),
	path('new', new_chat_list, name="new"),
	path('new/<slug>/', new_chat, name="new_chat"),
	path('<id>/dc/delete', delete_chat, name="delete_chat"),
	path('<slug>/dm/<id>', delete_message, name="delete_message"),

]

post/urls.py
from django.urls import path
from post.views import (
    create_post_view,
    edit_post_view,
    detail_post_view,
    delete_post_view,
    like_post,
    likes_view,
    PostLikeAPIToggle,
    CommentFormView,
    PostCommentApiForm,
)



app_name = 'post'

urlpatterns = [
    path('create', create_post_view, name="create_post"),
    path('<slug>/', detail_post_view, name="detail_post"),
    path('<slug>/edit', edit_post_view, name="edit_post"),
    path('<slug>/delete', delete_post_view, name="delete_post"),
    path('<slug>/like', like_post, name="like_post"),
    path('api/<slug>/like', PostLikeAPIToggle.as_view(), name="like_post_api"),
    path('<slug>/liked', likes_view, name="likes"),
    path('api/<slug>/comment/', PostCommentApiForm.as_view(), name="comment_post"),


]

activity/models.py
from django.db import models
from account.models import Account
from post.models import Post

NOTIFICATION_MESSAGE=(
	('following', 'started following you'),
	('like', 'liked your photo')
)

NOTIFICATION_TYPE=(
	('request', 'REQUEST_NOTIFICATION'),
	('following', 'FOLLOWING_NOTIFICATION'),
	('like', 'LIKE_NOTIFICATION'),

)
class Notification(models.Model):
	message 					= models.CharField(choices=NOTIFICATION_MESSAGE, null=True, max_length=100)
	notification_type			= models.CharField(choices=NOTIFICATION_TYPE, max_length=100)
	timestamp 					= models.DateTimeField(auto_now=True, editable=False)
	user						= models.ForeignKey(Account, on_delete=models.CASCADE, related_name='notifcation_for_user')
	notification_by				= models.ForeignKey(Account, on_delete=models.CASCADE, related_name='notifcation_by_user')
	post 						= models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)

	class Meta:
		ordering  = ('-timestamp',)

activity/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from activity.models import Notification
from account.models import Connection, Request


def all_notification_view(request):
	context = {}
	user = request.user
	
	notifications = Notification.objects.filter(user=user)
	context['authenticated'] = True
	status_list = []
	request_list = []
	for notification in notifications:
		if Connection.objects.filter(following=user, followers=notification.notification_by).exists():
			status_list.append(notification.notification_by)
		elif Request.objects.filter(request_by=user, target_user=notification.notification_by).exists():
			request_list.append(notification.notification_by)
	context['status_list'] = status_list
	context['request_list'] = request_list
	context['notifications'] = notifications
	context['response'] = 'all'

	return render(request, 'activity/notifications.html', context)


def request_notification_view(request):
	context = {}
	user = request.user
	notifications = Notification.objects.get(user=user, notification_type='request')
	context['notification'] = notification
	
	context['response'] = 'request'


	return render(request, 'activity/notifications.html', context)

activity/templates/activity/notifications.html
{% extends 'base.html' %}



{% load static %}

{% block content %}

<style type="text/css">
	.user_image {
  		border-radius: 50%;
  	}
  	p {
  		color: 	#ababab;
  		font-size: 13px;
	}
	.main-content{
		 box-shadow: 0 0 13px rgba(0, 0, 0, 0.4);
		 max-height: 400px;
		 overflow-y: auto;

	}
/*
	::-webkit-scrollbar {
	display: none;
	}*/
</style>

{% include 'snippets/buttons_css.html' %}



<div class="container">

	
	<div class="col-sm-8 offset-sm-2 main-content" style="background-color: white; border-radius: 20px;">
		<div class="row justify-content-center">
			<h4 class="mt-3 mb-0" style="font-size: 17px">Notifications</h4>
		</div>
		
		{% for notification in notifications %}
			<hr class="mt-1">
				<div class="row">

					<a style="text-decoration: none; font-size: 13px;" class="text-dark" href="{% url 'account_detail' notification.notification_by.slug %}">
						<img class="user_image mx-2" width= 40px height= 40px src="{{notification.notification_by.profile_picture.url}}">
					</a>
					<div class="col">
						<a style="text-decoration: none; font-size: 13px;" class="text-dark align-text-bottom" href="{% url 'account_detail' notification.notification_by.slug %}"><b>{{notification.notification_by.username}}</b></a>

						{% if notification.notification_type == 'request' %}
							<!-- <a style="text-decoration: none; font-size: 13px;" class="text-dark align-text-bottom" href="{% url 'account_detail' notification.notification_by.slug %}"><b>{{notification.notification_by.name}}</b></a> -->

							<a href="{% url 'cancel_request' notification.notification_by.slug %}" class="btn float-right delete-request-btn">Delete</a>
							<a href="{% url 'confirm_request' notification.notification_by.slug %}" class="btn float-right mr-2 pb-2 confirm-request-btn">Confirm</a>
							<p class="align-text-top mb-1 ">{{notification.notification_by.name}}</p>
							
						{% elif notification.notification_type == 'following' %}
							{% if notification.notification_by in status_list %}
								{{notification.notification_by}} 
								{% include 'snippets/modals/connection-modal.html' with user_profile=notification.notification_by %}
								<a href="{% url 'unfollow' notification.notification_by.slug%}" class="float-right following-btn button mr-2 pb-2">Following</a>
								<!-- <button  type="button"  data-toggle="modal" data-target="#exampleModalCenter" class="float-right following-btn button mr-2 pb-2">Following</button> -->

							{% elif notification.notification_by in request_list %}
								<a href="{% url 'unfollow' notification.notification_by.slug%}" class="following-btn button float-right mr-2 pb-2">Requested</a>
							{% else %}
								<a href="{% url 'follow' notification.notification_by.slug%}" class="float-right follow-btn button mr-2 pb-2">Follow</a>
							{% endif %}
							
							<p class="align-text-top">started following you</p>

						{% elif notification.notification_type == 'like' %}
							<a href="{% url 'post:detail_post' notification.post.slug %}" class="float-right mr-2 pb-2"><img src="{{notification.post.image.url}}" width= 40px height= 40px></a>
							<p class="align-text-top">liked your photo</p>

						{% endif %}


					</div>
					
				</div>

	{% endfor %}
	</div>


</div>

{% endblock %}