chat/urls.py
from django.urls import path
from chat.views import(
	message_view,
	inbox_view,
	new_chat_list,
	new_chat,
	delete_chat,
	delete_message,

)


app_name = 'chat'


urlpatterns = [
	path('<slug>/', message_view, name="message"),
	path('account/inbox', inbox_view, name="inbox"),
	path('new', new_chat_list, name="new"),
	path('new/<slug>/', new_chat, name="new_chat"),
	path('<id>/dc/delete', delete_chat, name="delete_chat"),
	path('<slug>/dm/<id>', delete_message, name="delete_message"),

]

post/urls.py
from django.urls import path
from post.views import (
    create_post_view,
    edit_post_view,
    detail_post_view,
    delete_post_view,
    like_post,
    likes_view,
    PostLikeAPIToggle,
    CommentFormView,
    PostCommentApiForm,
)



app_name = 'post'

urlpatterns = [
    path('create', create_post_view, name="create_post"),
    path('<slug>/', detail_post_view, name="detail_post"),
    path('<slug>/edit', edit_post_view, name="edit_post"),
    path('<slug>/delete', delete_post_view, name="delete_post"),
    path('<slug>/like', like_post, name="like_post"),
    path('api/<slug>/like', PostLikeAPIToggle.as_view(), name="like_post_api"),
    path('<slug>/liked', likes_view, name="likes"),
    path('api/<slug>/comment/', PostCommentApiForm.as_view(), name="comment_post"),


]

post/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_delete
from django.conf import settings
from django.dispatch import receiver
import string
import random





def upload_location(instance, filename, **kwargs):
	file_path = 'post/{author_id}/{caption}-{filename}'.format(
			author_id=str(instance.author_id), caption=str(instance.caption), filename=filename
		)
	# result = cloudinary.uploader.unsigned_upload(file_path, 'post', **options)
	return file_path


def generate_id():
        n = 11
        return ''.join(random.choices(string.ascii_uppercase + string.ascii_lowercase + string.digits, k=n))


class Post(models.Model):
	caption				= models.CharField(max_length=2200, null=False, blank=True)
	image				= models.ImageField(null=False, blank=False)
	date_published		= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated		= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author				= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	slug				= models.SlugField(blank=True, unique=True, max_length=11, default=generate_id)
	likes 				= models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')

	objects = models.Manager()

	def __str__(self):
		return self.slug

	def post_caption(self, caption):
		return caption

	def post_author(self, author):
		return author


class Comment(models.Model):
	post 			= models.ForeignKey(Post, on_delete=models.CASCADE)
	commenter		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	comment 		= models.CharField(max_length=2200, null=True, blank=False)
	date_commented	= models.DateTimeField(auto_now_add=True, verbose_name="date commented")

	def __str__(self):
		return str(self.commenter) + ": " + self.comment


@receiver(post_delete, sender=Post)
def submission_delete(sender, instance, **kwargs):
	instance.image.delete(False)


def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-" + instance.caption)

pre_save.connect(pre_save_blog_post_receiver, sender=Post)

post/forms.py
from django import forms
from post.models import Post, Comment
# import cloudinary
# import datetime
# import json


# def upload_image(instance, filename, **kwargs):
# 	file_path = 'post/{author}/'.format(
# 			author=str(instance.author)
# 	)
# 	img_request = cloudinary.uploader.unsigned_upload(filename, "insta-clone", 
# 	cloud_name = 'instacloud252', public_id=str(datetime.datetime.now()), folder=file_path)
# 	url = list(img_request.values())[14]
# 	return url

class CreatePostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('caption', 'image')

	# def save(self, commit=True):
	# 	post = self.instance
	# 	post.caption = self.cleaned_data['caption']
	# 	if self.cleaned_data['image']:
	# 		post.image = self.cleaned_data['image']
	# 		url = upload_image(filename=post.image, instance=post)
	# 		post.image = url
	# 	if commit:
	# 		post.save()
	# 	return post


class UpdatePostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('caption', 'image')


	def save(self, commit=True):
		post = self.instance
		post.caption = self.cleaned_data['caption']

		if self.cleaned_data['image']:
			post.image = self.cleaned_data['image']

		if commit:
			post.save()
		return post



class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ('comment',)

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.views.decorators.cache import cache_control
from django.db.models import Q
from post.forms import CreatePostForm,UpdatePostForm, CommentForm
from post.models import Post, Comment
from activity.models import Notification
from account.models import Account
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse_lazy

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
# import cloudinary
# import datetime
# import json


# def upload_image(instance, filename, **kwargs):
# 	file_path = 'post/{author}/'.format(
# 			author=str(instance.author)
# 	)
# 	img_request = cloudinary.uploader.unsigned_upload(filename, "insta-clone", 
# 	cloud_name = 'instacloud252', public_id=str(datetime.datetime.now()), folder=file_path)
# 	url = list(img_request.values())[14]
# 	return url



def create_post_view(request):
	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect('home')

	form = CreatePostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		author = Account.objects.filter(email=request.user.email).first()
		obj.author = author
		# if form.cleaned_data['image']:
		# 	image = form.cleaned_data['image']
		# 	url = upload_image(filename=image, instance=obj)
		# 	obj.image = url
		obj.save()
		context['success_message'] = "Successfully Posted"
		form = CreatePostForm()

	context['form'] = form

	return render(request, 'post/create_post.html', context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def edit_post_view(request, slug):
	context = {}

	user = request.user

	if not user.is_authenticated:
		return redirect("login")

	post = get_object_or_404(Post, slug=slug)

	if user != post.author:
		return redirect("home")

	if request.POST:
		form = UpdatePostForm(request.POST or None, request.FILES or None, instance=post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			post = obj
	form = UpdatePostForm(
			initial={
				"body" : post.caption,
				"image" : post.image,
			}
		)

	context['form'] = form	



	return render(request, 'post/edit_post.html', context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def detail_post_view(request, slug):
	context = {}

	user = request.user
	context['user'] = user
	if not user.is_authenticated:
		return redirect("login")

	try:
		post = Post.objects.get(slug=slug)
	except Post.DoesNotExist:
		return redirect("home")

	context['current_post'] = post

	# if Like.objects.filter(liker=user, post=post).exists():
	if user in post.likes.all():
		context['liked'] = 'liked'

	comment = Comment.objects.filter(post=post)
	context['comments'] = comment

	# like_count = Like.objects.filter(post=post).count()
	like_count = post.likes.all().count()
	context['like_count'] = like_count

	form = CommentForm(request.POST)
	if form.is_valid():
		obj = form.save(commit=False)
		obj.commenter = user
		obj.post = post
		obj.save()
		return redirect('post:detail_post' , post.slug)

	return render(request, 'post/detail_post.html', context)


from django.views.generic import FormView

from .forms import CommentForm
from .mixins import AjaxFormMixin


class CommentFormView(AjaxFormMixin,FormView):
    form_class = CommentForm
    template_name  = 'home/home.html'
    success_url = '/form-success/'



def delete_post_view(request, slug):
	user = request.user

	context = {}

	if not user.is_authenticated:
		return redirect("login")

	post = get_object_or_404(Post, slug=slug)
	
	if request.user != post.author:
		return redirect("home")

	deleted = 'Post deleted successfully'

	post.delete()

	return redirect('account_detail', user.slug)


def like_post(request, slug):
	user = request.user

	try:
		post = Post.objects.get(slug=slug)
		

	except Post.DoesNotExist:
		message.warning(
			request,
			'Post does not exist'
		)

	if user in post.likes.all():
		if(user != post.author):
			like_notification = Notification.objects.get(notification_type='like',user=post.author, notification_by=user, post=post)
			like_notification.delete()
		post.likes.remove(user)
	else:
		post.likes.add(user)
		if(user != post.author):
			like_notification = Notification.objects.create(notification_type='like',user=post.author, notification_by=user, post=post)
	
	return redirect('post:detail_post', post.slug)



class PostLikeAPIToggle(APIView):
	authentication_classes = (authentication.SessionAuthentication,)
	permission_classes = (permissions.IsAuthenticated,)

	def get(self, request, slug=None, format=None):
		post = get_object_or_404(Post, slug=slug)
		url_ = post.slug
		user = self.request.user
		updated = False
		liked = False
		if user.is_authenticated:
			if user in post.likes.all():
				if(user != post.author):
					like_notification = Notification.objects.get(notification_type='like',user=post.author, notification_by=user, post=post)
					like_notification.delete()
				liked = False
				post.likes.remove(user)

			else:
				post.likes.add(user)
				if(user != post.author):
					like_notification = Notification.objects.create(notification_type='like',user=post.author, notification_by=user, post=post)
				liked = True
			updated = True
		data = {
			"updated": updated,
			"liked": liked,
		}
		return Response(data)


class PostCommentApiForm(APIView):
	authentication_classes = (authentication.SessionAuthentication,)
	permission_classes = (permissions.IsAuthenticated,)

	def post(self, request, slug=None, format=None):
		post = get_object_or_404(Post, slug=slug)
		user = request.user
		if request.method == 'POST':
			if user.is_authenticated:
				form = CommentForm(request.POST)
				updated = False
				if form.is_valid():
					obj = form.save(commit=False)
					obj.commenter = user
					obj.post = post
					obj.save()
					updated = True
		data = {
			'updated': updated
		}
		return Response(data)



def likes_view(request, slug):
	user = request.user
	context = {}

	try:
		post = Post.objects.get(slug=slug)
	
	except Post.DoesNotExist:
		return redirect("home")

	likes = post.likes.all()

	context['users'] = likes
	context['response'] = "Likes"

	return render(request, 'account/connection.html', context)



def get_post_queryset(query=None):
	queryset = []
	queries = query.split(" ")
	for q in queries:
		posts = Post.objects.filter(
				Q(caption__icontains=q) 
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))

post/templates/post/create_post.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}
  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">


			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}
			

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- Body -->
				<div class="form-group">
					<label for="id_caption">Caption</label>
					<textarea class="form-control" rows="10" type="text" name="caption" id="id_caption" placeholder="Caption here..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="id_image">Image</label>
					<input  type="file" name="image" id="id_image" accept="image/*" required>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>
</div>


<script type="text/javascript">
	if(performance.navigation.type == 2){
		location.reload(true);
	}
</script>


{% endblock content %}

post/templates/post/detail_post.html
{% extends 'base.html' %}



{% block content %}
{% load static %}


<style type="text/css">
	.card{
		box-shadow: 0 0 13px rgba(0, 0, 0, 0.4);
		border: 1px solid black;
		padding-right: 0!important;
	}
	.container{
		padding-top: 50px;
		
	}
	@media(min-width: 630px){
		.container{
			padding-left: 30px;
			padding-right: 30px
		}
	}
	.delete-btn{
		float: right;
	}
	.dropdown-btn{
		margin-left: auto;
		font-size: 14px;
	}
	.card-text{
		font-size: 15px;
		color: black;
	}
	.card-img-top{

	}
	#view_comment{
		color: #999;
		font-size: 14px;
		font-weight: 700 !important;

	}
    .user_image{
    	border-radius: 50%;
    	width: 32px;
    	height: 32px;
    }
    .name-field{
    	color: black;
    	font-weight: 600;
    	font-size: 14px;
    }
    hr{
  /*  	margin-right: -20px;
    	margin-left: -20px;*/
    	margin: 12px -20px;
    }

    ::-webkit-scrollbar {
    width: 0px;
    background: transparent; /* make scrollbar transparent */
	}
   

</style>


<div class="container">
	<div class="row">
		<!-- Blog Post-->
		<div class="card pr-4">
			<div class="row no-gutters">
				<div class="col-md-6" style="background: black">

					<img class="card-img-top py-5" style="" src="{{current_post.image.url}}">
				</div>
				<div class="col-md-6 ">
					<div class="card-body">

						<!--Don't use safe when getting the text from the user. It enables them to add html css and js into the websites-->
						<div class="row" >

							<a style="text-decoration: none; font-size: 13px;" class="text-dark" href="{% url 'account_detail' user.slug %}">
								<img class="user_image ml-2 mr-3" src="{{user.profile_picture.url}}">
							</a>
							
							<p class="name-field">{{user}}</p>
							<span style="margin-left: 4px; margin-right: 4px;">•</span>
							<p class="name-field">Following</p>
							<!-- <span class="dropdown-btn">•••</span> -->
							<span data-toggle="modal" data-target="#exampleModalCenter" class="dropdown-btn mr-2">•••</span>
							
						</div>
						<hr>
						<div class="post-body-container">
							<div class="row">
								<img class="user_image ml-2 mr-3" src="{{user.profile_picture.url}}">
								<div class="col" class="col-auto">
									<div class="row">
										<p>
										<span class="name-field">{{user.username}} </span>
										<span class="card-text">{{current_post.caption|safe}}</span></p>
									</div>
								</div>
							</div>
						</div>


						
							<!-- {% if current_post.author == request.user %}
								<a href="{% url 'post:edit_post' current_post.slug %}" class="btn btn-primary">Update</a>

								<a href="{% url 'post:delete_post' current_post.slug %}" class="btn btn-danger delete-btn">Delete</a>
								
							{% endif %} -->


						</p>
						{% if liked %}
							<a class="btn btn-light like-btn" data-href="{% url 'post:like_post_api' current_post.slug %}">Unlike</a>
						{% else %}
							<a data-href="{% url 'post:like_post_api' current_post.slug %}" class="btn btn-light like-btn">Like</a>
						{% endif %}

						

						<a style="font-size: 18px" value='{{ like_count }}' class=" my-2 like-count text-dark" data-likes='{{ like_count }}' href="{% url 'post:likes' current_post.slug %}">{{like_count}} like{{like_count|pluralize}}</a>



						{% if comments.count > 2 %}
							<a id="view_comment"  value='{{ comments.count }}' onclick="showcomments()">View all {{comments.count}} comments</a>
							<div id="all_comments" style="display: none">
								{% for comment in comments %}
									<p style="font-size: 13px; border: 1px solid black"><b>{{comment.commenter}}</b> {{comment.comment}}</p>
								{% endfor %}
							</div>
						{% else %}
							{% for comment in comments %}
								<p style="font-size: 14px"><b>{{comment.commenter}}</b> {{comment.comment}}</p>
							{% endfor %}
						{% endif %}
						
					</div>
					<form class="ajax-form" id="myForm" method="post" data-url="{% url 'post:comment_post' current_post.slug %}" enctype="multiparts/form-data">
						{% csrf_token %}
						<div class="card-footer text-muted">
							<div class="form-group" id="form_id">
									<input class="form-control" type="text" name="comment" id="commentInput" placeholder="Add a comment...">
									<button class="submit-button btn-block" type="submit">Post</button>
								</div>
							</div>
							
						</div>
					</form>	
				</div>
			</div>

		</div>

		<!-- End Blog Post-->
	</div>
</div>
{% include 'post/snippets/like_js.html' %}





<script>
$(document).ready(function(){
    var $myForm = $('.ajax-form')
    $myForm.submit(function(event){
        event.preventDefault()
        var $formData = $(this).serialize()
        var $thisURL = $myForm.attr('data-url')
        console.log($thisURL)
        $.ajax({
            method: "POST",
            url: $thisURL,
            data: $formData,
            success: handleFormSuccess,
            error: handleFormError,
        })
    })

    function handleFormSuccess(data, textStatus, jqXHR){
        console.log(data)
        console.log(textStatus)
        console.log(jqXHR)
        var view_comment = $('#view_comment')
        var comments_count = parseInt(view_comment.attr('value'))
        newCount = comments_count + 1
        view_comment.text('View all ' + newCount + ' comments')
        view_comment.attr('value', newCount)
    }

    function handleFormError(jqXHR, textStatus, errorThrown){
        console.log(jqXHR)
        console.log(textStatus)
        console.log(errorThrown)
    }
})
</script>

<script type="text/javascript">
	function showcomments() {
		document.getElementById("view_comment").style.display = 'none';
		document.getElementById("all_comments").style.display = 'block';
	}
</script>
{% endblock content %}

post/templates/post/edit_post.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}
  	.submit-button{
  		max-width: 200px;
  	}
	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}
	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}
	.image-group:hover .image {
	  opacity: 0.3;
	}
	.image-group:hover .middle {
	  opacity: 1;
	}
	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- Body -->
				<div class="form-group">
					<label for="id_caption">Caption</label>
					<textarea class="form-control" rows="10" type="text" name="caption" id="id_caption" placeholder="Caption here...." 
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>

			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };
	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}

	// if(performance.navigation.type == 2){
	// 	location.reload(true);
	// }
</script>

{% endblock content %}