activity/urls.py
from django.urls import path
from activity.views import (
	all_notification_view,
	request_notification_view,
)



app_name = 'activity'


urlpatterns = [
	path('all/', all_notification_view, name='notifications'),
	path('requests/', request_notification_view, name='request_notifications')
]

chat/urls.py
from django.urls import path
from chat.views import(
	message_view,
	inbox_view,
	new_chat_list,
	new_chat,
	delete_chat,
	delete_message,

)


app_name = 'chat'


urlpatterns = [
	path('<slug>/', message_view, name="message"),
	path('account/inbox', inbox_view, name="inbox"),
	path('new', new_chat_list, name="new"),
	path('new/<slug>/', new_chat, name="new_chat"),
	path('<id>/dc/delete', delete_chat, name="delete_chat"),
	path('<slug>/dm/<id>', delete_message, name="delete_message"),

]

explore/urls.py
from django.urls import path
from explore.views import(
	suggest_accounts_view,
)


app_name = 'explore'

urlpatterns = [
	path('explore/', suggest_accounts_view, name="account_suggestion"),
]

templates/snippets/base_css.html
<style type="text/css">
	body{
		background-color: #fafafa;
  		/*font-family: "Proxima Nova", "Helvetica Neue", Helvetica, Arial, sans-serif;*/
  		font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
	}
</style>

templates/snippets/buttons_css.html
<style type="text/css">
	.button{
		border-radius: 4px;
		font-size: 14px;
		font-weight: 600;
  		height: 30px;
  		text-align: center;
  		align-self: center;
	}
	.delete-request-btn{
		border: 0.8px solid #c9c9c9;
		border-radius: 6px;
		width: 65px;
		height: 32px;
		font-size: 14px;
		text-align: center;
		align-items: center;
		font-weight: bold;
	}
	.confirm-request-btn{
		background-color: #1f8eed;
		width: 70px;
		height: 32px;
		color: white;
		font-size: 14px;
		text-align: center;
		font-weight: bold;
		padding-right: 60px;
	}
	.following-btn{
  		border: 1px solid #dbdbdb;
  		background: white;
  		color: #262626;
  		width: 85px;
  	}
  	.follow-btn{
  		background-color: #3897f0;
  		color: white;
  		width: 60px;
  	}
  	.follow-back-btn{
  		background-color: #3897f0;
  		color: white;
  		width: 60px;
  	}
  	.confirm-request-btn:hover{
		color:white;
	}
	.follow-btn:hover{
		color:white;
	}
	.follow-back-btn:hover{
		color:white;
	}
  	
  	a.button:hover{
  		color: #000;
  		text-decoration: none;
  	}
  	a.follow-btn:hover{
  		color: #FFF!important;
  	}
</style>

templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
		margin-top: 20px
	}
</style>

<!-- Footer-->
<div class="d-flex flex-row align-items-center footer bg-white shadow-lg">
	<p class="m-auto">Instagram Clone | 2019</p>
</div>
<!-- End Footer-->



<script>
$(document).ready(function () {
    $('[data-toggle="tooltip"]').tooltip();
});
</script>

templates/snippets/header.html
{% load static %}

<!-- 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css"> -->



<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">




<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/jquery-ui.js" type="text/javascript"></script>
<link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/themes/start/jquery-ui.css"
rel="stylesheet" type="text/css" />



<meta name="viewport" content="width=device-width, initial-scale=1.0">


<style type="text/css">
	@media (min-width: 768px) {
	  	html {
		    font-size: 16px;
		  }
		.nav-icons{
			margin-left: auto;
		}
	}
	@media (max-width: 768px){
		.search-bar {
			display: none;
		}
	}
	@media (max-width: 768px){
		nav{
			padding: 2px
		}
	}
	.container {
	  max-width: 960px;
	}
	.search-bar{
		max-width: 215px;
		width: 100%;
		margin: auto;
	}
	.form-control{
		text-align: center;
		background: #fafafa;
		max-height: 28px;
		font-weight: 100;

	}
	form{
		width: 100%
	}
	.vl{
		border-left: thin solid black;
		height: 27px
	}
	nav{
		margin-left: auto;
	}
	.logo-img{
		margin-left: 35px;
	}
	.nav-header{
		max-width: 100%;
		height: 77px;
		z-index: 1;
	}
	.sticky{
		position: fixed;
		top: 0;
		width: 100%;
		z-index: 5;
		height: 52px;
	}

</style>


	<nav id="header" class="fixed-top d-flex flex-md-row align-items-center px-xl-4 bg-white border-bottom shadow-sm nav-header">
	  
	  	<div class="row">
		  	<a class="logo-img text-dark mr-3" style="text-decoration: none;" href="{%url 'home'%}"><img src="https://i.imgur.com/q467Nqp.png"></a>
		  	<div class="vl"></div>
		  	<a class="logo-text text-dark ml-3 mr-md-5" style="text-decoration: none;" href="{%url 'home'%}"><img src="https://i.imgur.com/nLpWz7Q.png"></a>




		</div>

	  {% if request.user.is_authenticated %}
	  <div class="search-bar mr-2">
	  	<form onsubmit="return executeQuery();">
	  		<input type="text" class="form-control" name="q" id="id_q" placeholder="Search">
	  	</form>
	  </div>
	  {% endif %}

	  <div class="my-2 my-md-0 mr-lg-3 nav-icons" style="margin-left: auto;">
	  	{% if request.user.is_authenticated %}
	  		<a class="p-2 text-dark" href="{% url 'explore:account_suggestion' %}"><svg aria-label="Find People" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24"><path clip-rule="evenodd" d="M24 .5C37 .5 47.5 11 47.5 24S37 47.5 24 47.5.5 37 .5 24 11 .5 24 .5zm0 44c11.3 0 20.5-9.2 20.5-20.5S35.3 3.5 24 3.5 3.5 12.7 3.5 24 12.7 44.5 24 44.5zm-4.4-23.7c.3-.5.7-.9 1.2-1.2l14.8-8.1c.3-.1.6-.1.8.1.2.2.3.5.1.8l-8.1 14.8c-.3.5-.7.9-1.2 1.2l-14.8 8.1c-.3.1-.6.1-.8-.1-.2-.2-.3-.5-.1-.8l8.1-14.8zm6.2 5l4.3-7.8-7.8 4.3 3.5 3.5z" fill-rule="evenodd"></path></svg></a>
			<a class="text-dark p-2" href="{% url 'activity:notifications' %}"><svg aria-label="Activity Feed" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24"><path clip-rule="evenodd" d="M34.3 3.5C27.2 3.5 24 8.8 24 8.8s-3.2-5.3-10.3-5.3C6.4 3.5.5 9.9.5 17.8s6.1 12.4 12.2 17.8c9.2 8.2 9.8 8.9 11.3 8.9s2.1-.7 11.3-8.9c6.2-5.5 12.2-10 12.2-17.8 0-7.9-5.9-14.3-13.2-14.3zm-1 29.8c-5.4 4.8-8.3 7.5-9.3 8.1-1-.7-4.6-3.9-9.3-8.1-5.5-4.9-11.2-9-11.2-15.6 0-6.2 4.6-11.3 10.2-11.3 4.1 0 6.3 2 7.9 4.2 3.6 5.1 1.2 5.1 4.8 0 1.6-2.2 3.8-4.2 7.9-4.2 5.6 0 10.2 5.1 10.2 11.3 0 6.7-5.7 10.8-11.2 15.6z" fill-rule="evenodd"></path></svg></a>
			<a class="p-2 text-dark" href="{% url 'account_detail' user.slug %}"><svg aria-label="Profile" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24"><g><path d="M24 27c-7.1 0-12.9-5.8-12.9-12.9s5.8-13 12.9-13c7.1 0 12.9 5.8 12.9 12.9S31.1 27 24 27zm0-22.9c-5.5 0-9.9 4.5-9.9 9.9s4.4 10 9.9 10 9.9-4.5 9.9-9.9-4.4-10-9.9-10zM44 46.9c-.8 0-1.5-.7-1.5-1.5V42c0-5-4-9-9-9h-19c-5 0-9 4-9 9v3.4c0 .8-.7 1.5-1.5 1.5s-1.5-.7-1.5-1.5V42c0-6.6 5.4-12 12-12h19c6.6 0 12 5.4 12 12v3.4c0 .8-.7 1.5-1.5 1.5z"></path></g></svg></a>

			
		{% else %}
			<a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
			<a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
			<a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a> 
			
	    {% endif %}
	  </div>

	</div>
</nav>




<script type="text/javascript">
	window.onscroll = function() {myFunction()};

	var header = document.getElementById("header");

	// Get the offset position of the navbar
	var sticky = header.offsetTop + 50;

	// Add the sticky class to the header when you reach its scroll position. Remove "sticky" when you leave the scroll position
	function myFunction() {
	  if (window.pageYOffset > sticky) {
	  	// $('.nav-header').animate({paddingTop: '-=4px'}, 100);
	  	// $('.nav-header').animate({paddingBottom: '-=4px'}, 100);

	    header.classList.add("sticky");
	    $('.vl').css('visibility', 'hidden');
	    $('.logo-text').css('visibility', 'hidden');
	  } else {
	    header.classList.remove("sticky");
	   //  $('.nav-header').animate({paddingTop: '4px'}, 100);
	  	// $('.nav-header').animate({paddingBottom: '4px'}, 100);
	    $('.vl').css('visibility', 'visible');
	    $('.logo-text').css('visibility', 'visible');
	  }
	}
</script>


<script type="text/javascript">
	document.getElementById("id_q").value = '{{query}}'
</script>

<script>
	function executeQuery(){
		var query = document.getElementById("id_q").value;
		window.location.replace("http://127.0.0.1:8000/?q=" + query)
		return false
	}
</script>